### ISSUE TITLE
Hello i have this package working great, i have an issue

### ISSUE THREAD

**Issue by atta1234** [Cyber-Duck/laravel-excel#14]
how to export the headiing of table as well;

public function exportprovider(){

$yourCollection=Providerdata::all();

$excel = Exporter::make('Excel');
$excel->load($yourCollection);
return $excel->stream('Members.xlsx');
 }

currently it's noyt exporting the coloum name,

**Comment by SimoTod** [comment]
Hi @atta1234, this is the default behaviour but you can create a custom serialiser class and write your own logic. See https://github.com/Cyber-Duck/laravel-excel#advanced-usage
