### ISSUE TITLE
How to skip header (first & second row) when importing excel file

### ISSUE THREAD

**Issue by jarachanthan** [Cyber-Duck/laravel-excel#15]
I'm trying to import an .xlsx file in Laravel. What I want to achieve is to skip the header (first & second row) of the file.
```
$filepath = $request->file('file');
$excel = Importer::make('Excel');
$excel->hasHeader(true);
$excel->load($filepath)->setParser(new ParserModel())->getCollection();
$collection = $excel->getCollection();
```
this is working well with for one row header, but in my case I have two rows as header and how can I achieve this?

**Comment by SimoTod** [comment]
It's not supported but, as a workaround, Iif the transform function returns false, the row won't be added to the collection.

**Comment by jarachanthan** [comment]
Thanks for your reply.
I changed the code to solve my problem like this (unset the collect). 
`$collection = $excel->getCollection()->skip(1);`

**Comment by jarachanthan** [comment]
> It's not supported but, as a workaround, Iif the transform function returns false, the row won't be added to the collection.

Thanks for your reply.
I changed the code to solve my problem like this (unset the collect).
$collection = $excel->getCollection()->skip(1);
