### ISSUE TITLE
cell images are not shwoing in collection. 

### ISSUE THREAD

**Issue by bhagchandani** [Cyber-Duck/laravel-excel#17]
I have images in a cell. when I setSheet number and call the getCollection function on $excel object. only the data is printed. Is there any way I can get the images as well. 

Thanks

**Comment by SimoTod** [comment]
This library uses box/spout which unfortunately does not support images

**Comment by bhagchandani** [comment]
> This library uses box/spout which unfortunately does not support images

Thanks. I will close the issue now.
