### ISSUE TITLE
Import Excel with column headers

### ISSUE THREAD

**Issue by imyque** [Cyber-Duck/laravel-excel#7]
Hi,

This is not an issue.

I want to ask how I can use your plugin to import an excel sheet, where the first row contains the column headers. Then, I can use the headers to ref fields in a row.

name  |  age
--------------
Jane    |   9
Pet      |   7

$row->name

Thanks

**Comment by SimoTod** [comment]
Hi @imyque,

you can call `hasHeader(true)` before generating the collection.
```
$excel = Importer::make('Excel');
$excel->hasHeader(true);
$excel->load($filepath);
$collection = $excel->getCollection();
//THEN, FOR EXAMPLE
foreach ($collection as $row) {
     echo $row['name'];
}
```
Please note that the package generates a collection of arrays by default. 
If you'd like to use objects, you can set a custom parser like:
```
namespace your\namespace;

use Cyberduck\LaravelExcel\Parser\BasicParser;

class CustomParser extends BasicParser
{
    public function transform($row, $header)
    {
        //Use the Basic Parser and cast the result as object.
        return (object) parent::transform($row, $header);
    }
}
```
then in your application you can call
```
$excel = Importer::make('Excel');
$excel->hasHeader(true);
$excel->load($filepath);
$excel->setParser(new CustomParser);
$collection = $excel->getCollection();
//THEN, FOR EXAMPLE
foreach ($collection as $row) {
     echo $row->name;
}
```

Let me know if you have further questions or I can close the issue, thanks.

**Comment by imyque** [comment]
Thanks, SimoTod for your swift response.

If I want to Parser to cast the row into a Model, 

1. Will the header columns names have to match the Model's fields?
2. Will the parser transform method cast the row into the Model class instead of object?

Thanks

**Comment by SimoTod** [comment]
No, you cannot cast an array to a model in that way. You get the raw data and the column names then it's up to you how you code/map the data. The parser in this comment is just a quick example. The only requirement for the parser is to implement the right interface and the trasform method.
